from src.entities.entities import DetailedMovement
from src.entities.move_content import MoveNames, MoveDescriptions

DEFAULT_MOVE_LIST = [
    DetailedMovement(
        name=MoveNames.SLOW_LEFT_0,
        description=MoveDescriptions.SLOW_LEFT_0,
        index=0,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.SLOW_LEFT_1,
        description=MoveDescriptions.SLOW_LEFT_1,
        index=1,
        modifier=3
    ),
    DetailedMovement(
        name=MoveNames.SLOW_LEFT_2,
        description=MoveDescriptions.SLOW_LEFT_2,
        index=2,
        descent=True,
        flair=True,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.SLOW_STRAIGHT_0,
        description=MoveDescriptions.SLOW_STRAIGHT_0,
        index=3,
        descent=True,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.SLOW_STRAIGHT_1,
        description=MoveDescriptions.SLOW_STRAIGHT_1,
        index=4,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.SLOW_STRAIGHT_2,
        description=MoveDescriptions.SLOW_STRAIGHT_2,
        index=5,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.SLOW_RIGHT_0,
        description=MoveDescriptions.SLOW_RIGHT_0,
        index=6,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.SLOW_RIGHT_1,
        description=MoveDescriptions.SLOW_RIGHT_1,
        index=7,
        modifier=3
    ),
    DetailedMovement(
        name=MoveNames.SLOW_RIGHT_2,
        description=MoveDescriptions.SLOW_RIGHT_2,
        index=8,
        descent=True,
        flair=True,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_LEFT_0,
        description=MoveDescriptions.CRUISING_LEFT_0,
        index=9,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_LEFT_1,
        description=MoveDescriptions.CRUISING_LEFT_1,
        index=10,
        descent=True,
        flair=True,
        modifier=3
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_LEFT_2,
        description=MoveDescriptions.CRUISING_LEFT_2,
        index=11,
        descent=True,
        flair=True,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_STRAIGHT_0,
        description=MoveDescriptions.CRUISING_STRAIGHT_0,
        index=12,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_STRAIGHT_1,
        description=MoveDescriptions.CRUISING_STRAIGHT_1,
        index=13,
        flair=True,
        modifier=4
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_STRAIGHT_2,
        description=MoveDescriptions.CRUISING_STRAIGHT_2,
        index=14,
        flair=True,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_STRAIGHT_3,
        description=MoveDescriptions.CRUISING_STRAIGHT_3,
        index=15,
        flair=True,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_RIGHT_0,
        description=MoveDescriptions.CRUISING_RIGHT_0,
        index=16,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_RIGHT_1,
        description=MoveDescriptions.CRUISING_RIGHT_1,
        index=17,
        descent=True,
        flair=True,
        modifier=3
    ),
    DetailedMovement(
        name=MoveNames.CRUISING_RIGHT_2,
        description=MoveDescriptions.CRUISING_RIGHT_2,
        index=18,
        descent=True,
        flair=True,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.FAST_LEFT_0,
        description=MoveDescriptions.FAST_LEFT_0,
        index=19,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.FAST_LEFT_1,
        description=MoveDescriptions.FAST_LEFT_1,
        index=20,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.FAST_STRAIGHT_0,
        description=MoveDescriptions.FAST_STRAIGHT_0,
        index=21,
        modifier=0
    ),
    DetailedMovement(
        name=MoveNames.FAST_STRAIGHT_1,
        description=MoveDescriptions.FAST_STRAIGHT_1,
        index=22,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.FAST_STRAIGHT_2,
        description=MoveDescriptions.FAST_STRAIGHT_2,
        index=23,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.FAST_RIGHT_0,
        description=MoveDescriptions.FAST_RIGHT_0,
        index=24,
        modifier=1
    ),
    DetailedMovement(
        name=MoveNames.FAST_RIGHT_1,
        description=MoveDescriptions.FAST_RIGHT_1,
        index=25,
        modifier=1
    )
]
