from enum import Enum


class MoveNames(str, Enum):
    SLOW_LEFT_0 = "Slow Turn Left"
    SLOW_LEFT_1 = "Tight Bank Left"
    SLOW_LEFT_2 = "Weave Left"
    SLOW_STRAIGHT_0 = "Stall"
    SLOW_STRAIGHT_1 = "Weaving Turn Left"
    SLOW_STRAIGHT_2 = "Weaving Turn Right"
    SLOW_RIGHT_0 = "Slow Turn Right"
    SLOW_RIGHT_1 = "Tight Bank Right"
    SLOW_RIGHT_2 = "Weave Right"
    CRUISING_LEFT_0 = "Cruising Turn Left"
    CRUISING_LEFT_1 = "Wingover Left"
    CRUISING_LEFT_2 = "Sideslip Left"
    CRUISING_STRAIGHT_0 = "Straight Cruise"
    CRUISING_STRAIGHT_1 = "Immelmann Turn"
    CRUISING_STRAIGHT_2 = "Left Barrel Roll"
    CRUISING_STRAIGHT_3 = "Right Barrel Roll"
    CRUISING_RIGHT_0 = "Cruising Turn Right"
    CRUISING_RIGHT_1 = "Wingover Right"
    CRUISING_RIGHT_2 = "Sideslip Right"
    FAST_LEFT_0 = "Fast Turn Left"
    FAST_LEFT_1 = "Fast Bank Left"
    FAST_STRAIGHT_0 = "Fast Straight"
    FAST_STRAIGHT_1 = "Fast Straight Turn Left"
    FAST_STRAIGHT_2 = "Fast Straight Turn Right"
    FAST_RIGHT_0 = "Fast Turn Right"
    FAST_RIGHT_1 = "Fast Bank Right"


class MoveDescriptions(str, Enum):
    SLOW_LEFT_0 = "You make a gentle left turn, maintaining control at a slow speed."
    SLOW_LEFT_1 = "You perform a tight left bank, keeping your speed under control."
    SLOW_LEFT_2 = "You weave to the left, balancing your plane in a controlled manner."
    SLOW_STRAIGHT_0 = "You stall momentarily, holding your position in the air."
    SLOW_STRAIGHT_1 = "You make a weaving turn to the left, shifting your trajectory smoothly."
    SLOW_STRAIGHT_2 = "You make a weaving turn to the right, adjusting your path."
    SLOW_RIGHT_0 = "You make a gentle right turn, keeping a steady and slow pace."
    SLOW_RIGHT_1 = "You perform a tight right bank, maneuvering with precision."
    SLOW_RIGHT_2 = "You weave to the right, carefully balancing your plane's motion."
    CRUISING_LEFT_0 = "You cruise into a wide left turn, maintaining average speed."
    CRUISING_LEFT_1 = "You perform a wingover to the left, changing direction with agility."
    CRUISING_LEFT_2 = "You sideslip to the left, shifting your position in the air."
    CRUISING_STRAIGHT_0 = "You hold your plane straight and cruise ahead at an average speed."
    CRUISING_STRAIGHT_1 = "You perform an Immelmann turn, climbing and reversing direction."
    CRUISING_STRAIGHT_2 = "You execute a left barrel roll, showcasing your acrobatic skill."
    CRUISING_STRAIGHT_3 = "You execute a right barrel roll, spiraling smoothly through the air."
    CRUISING_RIGHT_0 = "You cruise into a wide right turn, maintaining average speed."
    CRUISING_RIGHT_1 = "You perform a wingover to the right, shifting direction with ease."
    CRUISING_RIGHT_2 = "You sideslip to the right, adjusting your position deftly."
    FAST_LEFT_0 = "You make a sharp left turn at high speed, testing your limits."
    FAST_LEFT_1 = "You bank sharply to the left, moving with rapid precision."
    FAST_STRAIGHT_0 = "You cruise straight at high speed, maintaining control."
    FAST_STRAIGHT_1 = "You make a fast turn to the left while cruising straight."
    FAST_STRAIGHT_2 = "You make a fast turn to the right while cruising straight."
    FAST_RIGHT_0 = "You make a sharp right turn at high speed, maneuvering deftly."
    FAST_RIGHT_1 = "You bank sharply to the right, executing a precise and rapid move."
